let suggestions = [
  "Axios syntax",
  "Babel",
  "Computer",
  "Coding",
  "Design a simple layout",
  "Products Filter and Search",
  "Tooltip using HTML-CSS",
  "DSA Practice",
  "Shopping Cart and Filter",
  "Curved Side-Menu using HTML-CSS",
  "Login Form in HTML & CSS",
  "Learn ReactJS",
  "ChakraUI",
  "Recursion",
  "Instagram uploads",
  "Youtube Shorts",
  "Figma Designs",
  "MongoDB concepts",
  "Express framework",
];
