let products = {
  data: [
    {
      productName: "Women Solid Longline Top",
      category: "Topwear",
      price: "349",
      image: "images/top-1.png",
    },
    {
      productName: "",
      category: "Jacket",
      price: "1699",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Jacket",
      price: "2199",
      image: "",
    },
    {
      productName: "",
      category: "Watch",
      price: "1190",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Watch",
      price: "1190",
      image: "",
    },
    {
      productName: "",
      category: "Topwear",
      price: "349",
      image: "",
    },
    {
      productName: "",
      category: "Topwear",
      price: "349",
      image: "",
    },
    {
      productName: "",
      category: "Jacket",
      price: "2199",
      image: "",
    },
    {
      productName: "",
      category: "Jacket",
      price: "2199",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Bottomwear",
      price: "313",
      image: "",
    },
    {
      productName: "",
      category: "Watch",
      price: "1190",
      image: "",
    },
    {
      productName: "",
      category: "Jacket",
      price: "2199",
      image: "",
    },
    {
      productName: "",
      category: "Topwear",
      price: "349",
      image: "",
    },
    {
      productName: "",
      category: "Topwear",
      price: "349",
      image: "",
    },
    {
      productName: "",
      category: "Watch",
      price: "1190",
      image: "",
    },
  ],
};
